# Generated by Django 4.2.3 on 2023-07-27 12:29
from django.core.management import call_command
from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    call_command("loaddata", "dump_data.json")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_task_created_alter_task_deadline"),
    ]

    operations = [RunPython(func)]
